### ISSUE TITLE
apply_delta_update fails on unexpected patch file data

### ISSUE THREAD

**Issue by snelson-senet** [janjongboom/lorawan-fota-signing-tool#1]
This failure happens when applying the delta update

Expected ESC but got EF
Positions are, source=0 patch=1 new=0
[WARN][LWUC]: apply_delta_update failed 1_

I've tracked down the issue to bad format of the diff returned by the fota-lorawan-signing-tool.
Looking at the implementation, the diff is in the stdout returned by spawnSync(jdiff.js) and for some reason it's not correct; However, when the jdiff command is run with the outfile option set, the diff in the outfile is correct.

I changed the tool to pass jdiff an outfile, and to get the diff from the file. With this change, delta updates are now working for me.

**Comment by janjongboom** [comment]
@snelson-senet Could you send me the old and the new firmware files? You can drop them at jan.jongboom@arm.com and I'll fix it.

**Comment by janjongboom** [comment]
This has been fixed in 105804d2bab98e1561171dcbf8cc61f23dd836b8
