### ISSUE TITLE
Error generating keypair

### ISSUE THREAD

**Issue by kvkc97** [janjongboom/lorawan-fota-signing-tool#3]
I need to create a public/private key pair using Node.js 8. I have installed lorawan-fuota-signing-tool and gave the command "lorawan-fota-signing-tool create-keypair -d example.com -m awesome-2000" to generate keypair. An error occured as in the attachment and no files are generated in the folder .fota-keys. When I try further to generate keypair, error is displayed that overwriting of existing certificates is not possible.
![image](https://user-images.githubusercontent.com/73599382/103883022-a3832f00-5102-11eb-81eb-4d9eb04b5bee.png)

I would also like to confirm if the domain name and device model name are specific or can be given by the user. I have given them as example.com and awesome-2000 currently.

**Comment by kvkc97** [comment]
Can I get an update on this.. @janjongboom

**Comment by Marcel-Ball** [comment]
Hi @kvkc97,
I am having the same issue.  Did you manage to reslove it?

**Comment by kvkc97** [comment]
@Marcel-Ball No I couldn't solve it

**Comment by Sunembrace** [comment]
Hi, have you fixed this issue?

**Comment by kvkc97** [comment]
No issue is not solved

**Comment by Sunembrace** [comment]
Then, could you please tell me how to fix it? I met the same, thank you so much!

**Comment by kvkc97** [comment]
I could not solve the issue. Sorry.

**Comment by Sunembrace** [comment]
Hi kvkc97, I have solved it, the reason is that openssl is not installed well. You have to download it, then add its "bin" to the "environment variale", and compile it in the openssl command line (anyway, openssl has to be installed), where you can find information in this link (https://www.cnblogs.com/dshvv/p/12271280.html). Hope this could help you.

**Comment by kvkc97** [comment]
Thanks for the solution.
